Generate question#8
nowakprojects/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #34
Opened 2020-12-28 09:48 UTC by jurecki

2021-01-02 17:54 UTC, PiotrWR requested changes

2021-01-02 17:54 UTC, PiotrWR commented on test/questionGenerator.spec.js
> +};
Zazdroszczę Tobie umiejętności pisania fajnych testów! :)))

2021-01-03 19:26 UTC, nowakprojects commented on src/app/QuestionGenrator.js
> +    //Zwróc uwagę, że fetchData zwrac Promise i Twoja funkcja kończy się - zwraca result zanim jeszcze fetchData się wykona. Trzeba poczekać na rezultat.
@Szambelan @jurecki @PiotrWR @tomdworniczak @DomiZet To kto się tego podejmie :) ? To jedyne rzecz praktycznie do dokończenia.

2021-01-04 15:43 UTC, nowakprojects approved these changes

2021-01-04 15:49 UTC, PiotrWR approved these changes

2021-01-04 15:49 UTC, Szambelan approved these changes

2021-01-04 15:50 UTC, merged