#59 Add common render function, which can be used to render any component inside another
nowakprojects/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #61
Opened 2021-01-08 14:10 UTC by nowakprojects

It's also possible to assign additional class by this function.

closes #59

2021-01-08 23:34 UTC, DomiZet approved these changes

2021-01-09 00:04 UTC, PiotrWR requested changes
Do poprawy. Brak możliwości usunięcia elementu. Reszta fajnie napisana.
Szczegóły:
Co w momencie jak będziemy chcieli usunąć dany komponent?
Nie ma dodanej opcji, aby "odrenderować" elementy, albo wygenerować nowe na ich miejsce.

@PiotrWR PiotrWR Collaborator Pending
Co w sytuacji jak będziemy chcieli stworzyć przyciski z nowymi wartościami? Albo wygenerować nową zawartość?
Nie moge znaleźć funkcji usuwającej.
Ale przyznam, że może po prostu jej nie widzę, a jest gdzieś ukryta!

@PiotrWR PiotrWR Collaborator Pending
Usuwanie widze tylko w "navMenu";
Ale to właściwie tylko w opcji generowania nowego elementu

@PiotrWR PiotrWR Collaborator Pending
To co wyżej :)

2021-01-09 00:04 UTC, PiotrWR commented on src/app/rendering.js
> +}
Usuwanie widze tylko w "navMenu";

2021-01-09 00:04 UTC, PiotrWR commented on src/app/App.js
> +  });
Ładne, jak usunąć ten przycisk?

2021-01-09 00:04 UTC, PiotrWR commented on src/app/rendering.js
> +}
<important>
To co wyżej :)

2021-01-09 00:57 UTC, PiotrWR approved these changes

2021-01-09 00:59 UTC, merged

2021-01-09 01:02 UTC, nowakprojects commented
Dzięki za komentarz :) Takich funkcjonalnosci nie było wcześniej, a tutaj zrobiłem tylko refactor. Czyli zmieniam strukture kodu (w tym wypadku usuwam duplikacje), ale nie jego zachowanie.
Ale racja - to nam się przyda i warto dorobić. Coś podobnego jest w renderNavBar no i tam zostawiłem ta logikę, bo już była zrobiona przez Ciebie.

Zastanawia mnie tylko czy usuwanie i dodawanie komponentu przy jakiejś zmianie to dobra droga. Ogólnie jestem za! (niż modyfikowaniem) ale w tym wypadku... Chyba byłoby trzeba iść w stronę modyfikacji. Załóżmy że na zmianę jakiegoś stanu chcemy zrobić jakąś animacje? Usuwając i dodając chyba nie da rady. Choć będąc szczerym nigdy nie dodawałem animacji w czystym JSie.